# Generated by Django 2.2.5 on 2019-11-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doctype',
            field=models.CharField(default='err', max_length=5),
        ),
    ]
