# Generated by Django 2.2.5 on 2019-11-23 08:04

from django.db import migrations, models
import file2.models


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0003_auto_20191114_1840'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', file2.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
