# Generated by Django 2.2.5 on 2019-09-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0003_remove_document_printjobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='printJobStatus',
            field=models.IntegerField(default=0),
        ),
    ]
