# Generated by Django 2.2.5 on 2019-12-02 13:29

from django.db import migrations, models
import file2.models


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0004_auto_20191123_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(auto_now_add=True)),
                ('ipaddress', models.CharField(default='err', max_length=100)),
                ('data', models.CharField(default='err', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=file2.models.Document.get_document_path),
        ),
    ]
