# Generated by Django 2.2.5 on 2019-12-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0005_auto_20191202_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlanalytics',
            name='temp_user_id',
            field=models.CharField(default='err', max_length=200),
        ),
    ]
