# Generated by Django 2.2.5 on 2019-09-28 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0005_document_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='filename',
        ),
    ]
