# Generated by Django 2.2.5 on 2019-12-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0006_urlanalytics_temp_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='err', max_length=200)),
                ('student_phone', models.CharField(default='err', max_length=200)),
                ('student_branch', models.CharField(default='err', max_length=200)),
            ],
        ),
    ]
