# Generated by Django 2.2.5 on 2019-12-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0008_urlanalytics_temp_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='promo_code',
            field=models.CharField(default='no_promo', max_length=30),
        ),
    ]
