# Generated by Django 2.2.5 on 2019-12-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0009_document_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(default='branch', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='college',
            field=models.CharField(default='clg', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='phone', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.CharField(default='year', max_length=100),
        ),
    ]
