# Generated by Django 2.2.5 on 2019-12-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0010_auto_20191215_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlanalytics',
            name='temp_user_branch',
        ),
        migrations.AddField(
            model_name='urlanalytics',
            name='student_email',
            field=models.CharField(default='err', max_length=200),
        ),
    ]
