# Generated by Django 2.2.5 on 2020-01-01 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0012_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_shops', to=settings.AUTH_USER_MODEL),
        ),
    ]
