# Generated by Django 2.2.5 on 2020-01-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0013_document_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='user_id_2',
            field=models.IntegerField(default=0),
        ),
    ]
