# Generated by Django 2.2.5 on 2020-01-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0014_shop_user_id_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='print_cost',
            field=models.FloatField(default=0),
        ),
    ]
