# [START django_app]
runtime: python37

# TODO: change service and DJANGO_SETTINGS_MODULE based on dev or prod deploy

service: api
# service: dev-api

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "Preasy-1ce7a4bf603e.json"
  DJANGO_SETTINGS_MODULE: myporject.prod_settings
  # DJANGO_SETTINGS_MODULE: myporject.dev_settings
handlers:
# This configures Google App Engine to serve the files in the app's
# static directory.
- url: /static
  static_dir: static/
# This handler routes all requests not caught above to the main app.
# It is required when static routes are defined, but can be omitted
# (along with the entire handlers section) when there are no static
# files defined.
- url: /.*
  script: auto
# [END django_app]
