# Generated by Django 2.2.5 on 2019-09-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='PrintJobStatus',
            field=models.IntegerField(default=0),
        ),
    ]
