# Generated by Django 2.2.5 on 2019-09-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0002_document_printjobstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='PrintJobStatus',
        ),
    ]
