# Generated by Django 2.2.5 on 2019-09-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file2', '0004_document_printjobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(default='myfile', max_length=10),
        ),
    ]
